spring:
  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
      hibernate:
          ddl-auto: validate

server:
  ssl:
      key-store: classpath:${KEYSTORE_PATH} #.jks keystore
      key-store-password: ${KEYSTORE_PASSWORD}
  port: ${SERVER_PORT}