spring:
  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
      hibernate:
          ddl-auto: validate

server:
  ssl:
      enabled: true
      key-store-type: JKS
      key-store: classpath:${KEYSTORE_PATH} #.jks keystore
      key-store-password: ${KEYSTORE_PASSWORD}
      certificate: classpath:${CERTIFICATE_PATH} #.pem public key
  port: ${SERVER_PORT}